component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: module_core
      name: Core
      paths:
        - "Core/**"
      statuses:           # the core component has its own statuses
        - type: project
          target: 90%
          threshold: 5%
        - type: patch
    - component_id: module_app
      name: Main App
      paths:
        - "FlickrFindr/**"
coverage:
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 10%
        # flags: 
        #   - unit
        # paths: 
        #   - "src"
       # advanced settings
        # branches: 
        #   - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        target: 60%
        threshold: 20%
comment:
  layout: "header, diff, flags, components"