coverage:
  status:
    project:
      default:
        # basic
        target: 60%
        threshold: 10%
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 10%
