coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      target: 80%
    patches:
      default:
        target: 100%
        threshold: 1%
  status:
    project:
      default: off
    patches:
      "app/": default
      "lib/": default
    changes: main...*

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no

comment:
  layout: "header, diff, changes, files"

files:
  include:
    - "**/*.swift"
    - "**/*.m"
    - "**/*.mm"
  exclude:
    - "**/Tests/**"

