name: on_push.yml

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Test & Upload Coverage Report
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: | 
          xcodebuild \
            -project FlickrFindr.xcodeproj \
            -scheme FlickrFindr \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' \
            test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          swift: true
          swift_project: FlickrFindr
          functionalities: fixes
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
